version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install checkov boto3
  
  pre_build:
    commands:
      - echo "Running NIST 800-53 compliance scan with Checkov..."
      - checkov -f sample-s3.tf --framework terraform --output json --output-file-path . || true
      - echo "Checkov scan completed"
  
  build:
    commands:
      - echo "Analyzing results with AI..."
      - python ai-analyzer.py results_json.json
      - |
        if [ $? -ne 0 ]; then
          echo "❌ NIST 800-53 compliance scan FAILED - Pipeline blocked"
          exit 1
        fi
      - echo "✓ All NIST 800-53 checks passed - Deployment allowed"

artifacts:
  files:
    - results_json.json
    - compliance-report.txt
  name: compliance-scan-results
