version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install prowler boto3
  
  pre_build:
    commands:
      - echo "Running NIST 800-53 compliance scan with Prowler..."
      - prowler aws --compliance nist_800_53_revision_5_aws --output-formats json-ocsf --output-directory . || true
      - find . -name "*.ocsf.json" -type f
      - echo "Prowler scan completed"
  
  build:
    commands:
      - echo "Analyzing results with AI..."
      - python ai-analyzer.py $(find . -name "*.ocsf.json" -type f | head -1)
      - |
        if [ $? -ne 0 ]; then
          echo "❌ NIST 800-53 compliance scan FAILED - Pipeline blocked"
          exit 1
        fi
      - echo "✓ All NIST 800-53 checks passed - Deployment allowed"

artifacts:
  files:
    - "**/*.ocsf.json"
    - compliance-report.txt
  name: compliance-scan-results
