version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install checkov boto3
  
  pre_build:
    commands:
      - echo "Running NIST 800-53 compliance scan with Checkov..."
      - checkov -f sample-s3.tf --framework terraform --output json --output-file-path . || true
      - |
        if [ ! -f results_json.json ]; then
          echo "❌ Checkov failed to generate results"
          exit 1
        fi
      - echo "Checkov scan completed"
  
  build:
    commands:
      - echo "Analyzing results with AI..."
      - python ai-analyzer.py results_json.json

artifacts:
  files:
    - results_json.json
    - compliance-report.txt
  name: compliance-scan-results
